apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-proxy-be
    entity: product
    group: product
    subgroup: product
    type: backend-proxy-server
  name: nginx-proxy-be
  namespace: product-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy-be
      entity: product
      group: product
      subgroup: product
      type: backend-proxy-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-proxy-be
        entity: product
        group: product
        subgroup: product
        type: backend-proxy-server
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
 #           cpu: 500m 
            memory: 1Gi
          limits:
#            cpu: 2
            memory: 1Gi
status: {}
