apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy-server
  labels:
    app: proxy-server
    region: delhi
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
     requests:
      memory: "128Mi"
      cpu: "250m"
     limits:
       memory: "128Mi"
       cpu: "250m"
    ports:
     - containerPort: 80
