apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    creationTimestamp: null
    name: product-ns-quota-medium
    namespace: product-be
  spec:
    hard:
      limits.cpu: "4"
      limits.memory: 2Gi
      requests.cpu: "4"
      requests.memory: 2Gi
      pods: 2
    scopeSelector:
      matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["medium"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    creationTimestamp: null
    name: product-ns-quota-high
    namespace: product-be
  spec:
    hard:
      limits.cpu: "4"
      limits.memory: 4Gi
      requests.cpu: "4"
      requests.memory: 4Gi
      pods: 4
    scopeSelector:
      matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["high"]
