apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: product-ns-quota-low
  namespace: product-be
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
    requests.cpu: "2"
    requests.memory: 1Gi
    pods: 2
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values: ["low"]
