apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-proxy-be
    entity: product
    group: product
    subgroup: product
    type: backend-proxy-server
  name: nginx-proxy-be
  namespace: product-be
spec:
  ports:
  - name: "http-port"
    port: 80
    protocol: TCP
    targetPort: 80
  - name: "https-port"
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-proxy-be
    entity: product
    group: product
    subgroup: product
    type: backend-proxy-server
  type: NodePort
status:
  loadBalancer: {}
