apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cron-job-nginx
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cron-job-nginx
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            name: cron-job-nginx
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * * *'
status: {}
