apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-example
  labels:
    type: httpd-fe
    app: httpd-fe
spec:
  replicas: 8
  selector:
    matchLabels:
      type: httpd-fe
      app: httpd-fe
  template:
    metadata:
      name: httpd-fe-example
      labels:
        type: httpd-fe
        app: httpd-fe
    spec:
      containers:
      - name: httpd-example
        image: httpd:2.4.41-alpin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
