apiVersion: v1
kind: ReplicationController
metadata:
  name: py-proto-rc
  labels:
    app: py-proto-rc
    desc: set-replication-by-rc
spec:
  replicas: 3
  template:
    metadata:
      name: py-proto-service
      labels:
        app: py-proto-service
        type: back-end
        desc: py-prtoto-backend-service
    spec:
      containers:
      - name: py-proto-redis-example
        image: saurabhsa/py-protobuf-example:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis-16876.c212.ap-south-1-1.ec2.cloud.redislabs.com"
        - name: REDIS_PORT
          value: "16876"
        - name: REDIS_P
          value: "dkk1a9fV7alQv5OpCDRQEnoZArahoTzB"
