apiVersion: v1
kind: Service
metadata:
  name: svc-py-proto
  labels:
    app: py-proto
    description: py-proto-node-service
spec:
  ports:
  - port: 5000
  selector:
    app: py-proto
  type: NodePort
