apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-py-proto
    type: backend
  name: svc-py-proto
  namespace: py-proto
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    image: py-protobuf-example
    type: backend
  type: NodePort
status:
  loadBalancer: {}
