apiVersion: v1
kind: Service
metadata:
  name: svc-httpd
  labels:
    app: svc-httpd-app
    type: back-end
spec:
  type: NodePort
  selector:
    type: httpd-fe
    app: httpd-fe
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008 
