apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-py-protobuf-rest-api
    tier: backend
    type: API
    sub-type: REST
    environment: development
  name: svc-py-proto
#  namespace: py-proto
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: app-port
  selector:
    app: py-protobuf-rest-api
    tier: backend
    type: API
    sub-type: REST
    environment: development
  type: ClusterIP
status:
  loadBalancer: {}
