apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-py-proto
  labels:
    tier: backend
    type: API
    sub-type: REST
    environment: development
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/tmp/log/pyproto/"
